title: ことえりブログ
description: > # this means to ignore newlines until "baseurl:"
  日記や技術系の記事を書きます。
  Linux, AWS系がメイン。
#permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "" #if your site has a twitter account, enter it here

# Author Settings
author: kter # add your name
author-img: kter.png # add your photo
about-author:  # add description
twitter: kter # add your Twitter handle
facebook: # add your Facebook handle
github: kter # add your Github handle
linkedin: # add your Linkedin handle
email: me@kter.jp # add your Email address

# Disqus
discus-identifier: kotoeriburogu # add your discus identifier

# Tracker
analytics: UA-102810695-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "vendor"]
