version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3.6-alpine3.4

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: setup gcloud
          command: |
            apk update 
            apk add -y curl python
            curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-170.0.1-linux-x86_64.tar.gz | tar zx
            echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
            google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            google-cloud-sdk/bin/gcloud config set project personalprojects-189010
            google-cloud-sdk/bin/gcloud --quiet config set container/cluster main-01
            google-cloud-sdk/bin/gcloud config set compute/zone us-west1-a
            google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials main-01
            google-cloud-sdk/bin/gcloud --quiet components install kubectl
      - run:
          name: setup docker
          command: |
            apk install -y docker

      - run:
          name: setup docker
          command: docker login -u $DOCKER_USER --password-stdin <<< $DOCKER_PASS

      - run:
          name: setup jekyll
          command: bundle install --path vendor/bundle
      - run:
          name: build html
          command: bundle exec jekyll build

      - run:
          name: deploy
          command: docker build -t kter/blog:$CIRCLE_SHA1 .
      - run:
          name: deploy
          command: docker tag kter/blog:$CIRCLE_SHA1 kter/blog:latest
      - run:
          name: deploy
          command: docker push kter/blog:$CIRCLE_SHA1
      - run:
          name: deploy
          command: docker push kter/blog:latest
      - run:
          name: deploy
          command: kubectl set image deployments/blog blog=kter/blog:$CIRCLE_SHA1
      - run:
          name: deploy
          command: kubectl rollout status deployment/blog

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
