version: 2
machine:
  environment:
    PROJECT_NAME: PersonalProjects
    CLUSTER_NAME: main-01
    CLOUDSDK_COMPUTE_ZONE: us-west1-a
    DEBIAN_FRONTEND: noninteractive
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: setup dependencies
          # https://circleci.com/docs/1.0/google-auth/
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run:
          name: setup dependencies
          command: gcloud --quiet components update
      - run:
          name: setup dependencies
          command: gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - run:
          name: setup dependencies
          command: gcloud config set project personalprojects-189010
      - run:
          name: setup dependencies
          command: gcloud --quiet config set container/cluster $CLUSTER_NAME
      - run:
          name: setup dependencies
          command: gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
      - run:
          name: setup dependencies
          command: gcloud --quiet container clusters get-credentials $CLUSTER_NAME
      - run:
          name: setup dependencies
          command: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: build html
          command: bundle exec jekyll build

      - run:
          name: deploy
          command: docker build -t kter/blog:$CIRCLE_SHA1 .
      - run:
          name: deploy
          command: docker tag kter/blog:$CIRCLE_SHA1 kter/blog:latest
      - run:
          name: deploy
          command: docker push kter/blog:$CIRCLE_SHA1
      - run:
          name: deploy
          command: docker push kter/blog:latest
      - run:
          name: deploy
          command: kubectl set image deployments/blog blog=kter/blog:$CIRCLE_SHA1
      - run:
          name: deploy
          command: kubectl rollout status deployment/blog

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
